### ISSUE TITLE
Screenshot shows activity despite it is closed

### ISSUE THREAD

**Issue by tererecool** [jraska/Falcon#15]
I have a test that closes the main activity and then takes a screenshot. On this the activity passed as function parameter can be seen, despite in reality the home dashboard of the phone is shown, is this because the screenshot function uses internally the espresso screenshot function and not UiDevice.takescreenshot()? Is there a way I can use Falcon and get what I am really seeing on the screen?

**Comment by jraska** [comment]
Hi,

Falcon takes the screenshot of the activity passed into constructor. It has no information what is actually visible on the screen outside you application. For example it will never take screenshot of homepage or system screens.

It basically draws Views of your app into bitmap, so it does the screenshot of what is passed into the function.
