### ISSUE TITLE
When screen orientation is landscape, screenshot taken previously activity (portrait) also.

### ISSUE THREAD

**Issue by snechiporenko** [jraska/Falcon#17]
![screenshot 12](https://cloud.githubusercontent.com/assets/5830975/20347849/89350aba-ac0b-11e6-9f41-95b388d3959a.png)

**Comment by jraska** [comment]
Hi, thank you for reporting this, sounds like a bug.

I will look into it once I got a time. What Falcon does is just taking all attached windows from WindowManager and smash them into screenshot. Probably if there is some Activity below which is not rotated it is taken to screenshot as well.

**Comment by nsagnett** [comment]
Hi there !

It's just view visibility issue. Before add a new ViewRootData elements in the result list, you can check if view is shown (line 218):
```
if (view == null && view.isShown()) {
        Log.e(TAG, "null View stored as root in Global window manager, skipping");
        continue;
}

```
It works for me.

**Comment by jraska** [comment]
@nsagnett Thank you very much for the suggestion. Works and was tested. I will release new version with fix soon.
