### ISSUE TITLE
Can we not throw UnableToTakeScreenshotException?

### ISSUE THREAD

**Issue by jaredsburrows** [jraska/Falcon#19]
Can we not throw `UnableToTakeScreenshotException`? See https://github.com/jraska/Falcon/blob/master/falcon/src/main/java/com/jraska/falcon/Falcon.java#L65.

I am seeing a few tests fail because of failing to take a screenshot. The tests I am seeing fail are usually very stable. Can we just log the screenshot failure? The screenshots are nice to have but I do not have to have them. I just want my assertions to pass.

**Comment by jraska** [comment]
Hello,

Couldn't you wrap your screenshot calls into try catch with `UnableToTakeScreenshotException`?

I don't want to change it now, because the exception is now basically part of public API.6

**Comment by jaredsburrows** [comment]
@jraska When you have so many tests, that could be alot of wrapping. I am just asking to remove that line, if it fails, it can fail gracefully.

**Comment by jraska** [comment]
I can understand what you mean, but I prefer exception agains silently doing nothing. Logging is not visible enogh for me, but that is just about opinion.

Anyway some people might be already doing this wrapping and removing the exception can be then breaking change, which is the main reason why I will not do that, sorry. It would mean version 2.0.

**Comment by jaredsburrows** [comment]
Alright, thanks. I saw a few builds break because of this exception. I am not sure if it was the emulators or the test itself. Either way, I just wanted to report this to get some context. Thanks for answering. Great library by the way!

**Comment by jraska** [comment]
Thanks for using it and for feedback. :)
