### ISSUE TITLE
What about Here Maps?

### ISSUE THREAD

**Issue by harcoPro** [jraska/Falcon#2]
What about Here Maps?

**Comment by jraska** [comment]
Hello, I cannot see what rendering technique they use for drawing maps in their MapView documentation.

It would be possible to say only by inspecting their source code, but I expect they use OpenGL drawing for their maps, which means it would not be possible for Falcon library to capture the map layer.
Do you use their maps SDK?

**Comment by jraska** [comment]
Closing the issue. Maps use most probably OpenGL rendering which makes impossible for Falcon to capture their data.
