### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by tir38** [jraska/Falcon#35]
Can you update the README to make it clear that you still need to declare

```
androidTestImplementation 'com.jraska:falcon:2.0.1'
```

even if you are using 

```
androidTestImplementation 'com.jraska:falcon-spoon-compat:2.0.1'
```

I initially didn't include the `falcon` dependency since I assumed that it would be pulled in as part of `falcon-spoon-compat`. But when I did I got the following runtime error:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/jraska/falcon/Falcon;
    at com.jraska.falcon.FalconSpoonRule.screenshot(FalconSpoonRule.java:42)
...
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.jraska.falcon.Falcon" on path: DexPathList[[...]]
```

**Comment by jraska** [comment]
Hello, thanks for reporting this. I will fix this once there will be a bit of time.

**Comment by jraska** [comment]
Finally done ;) Thanks again
