### ISSUE TITLE
Falcon enhancement to work with AirBnb's Lottie animations

### ISSUE THREAD

**Issue by nikoskyr** [jraska/Falcon#46]
Hello,

I am trying to take multiple screenshots from a Lottie animation which is used in my app but it seems that Falcon takes a screenshot only from the very first instance of the animation and not the whole movement.

Is it a known issue? Can the Falcon be enhanced in order to cover this incompatibility?

Thanks a lot in advance!!!

Best regards,
Nikos

**Comment by jraska** [comment]
Hello Nikos,

Thanks for using Falcon and raising the issue ;)

Unfortunately I don't think this is possible for Falcon to solve. 

Falcon works basically by delegating on views drawing themselves into Canvas `View.draw(Canvas canvas)` method. Therefore delegating to `LottieAnimationView` in this case. I would guess Lottie is quite advanced with animations, which goes beyond this simple drawing.

Similar problem is with surface views or with native views like Google Maps for example.

Therefore I unfortunately don't see a way to solve this for now. I would be happy for any ideas or samples.

Josef

**Comment by nikoskyr** [comment]
Hello Josef,

Thanks a lot for the prompt reply.

Fully understood. If we can't solve this problem, then I guess we should close the issue.
Unfortunately, I can't think anything to find a workaround about this.

Best regards,
Nikos

**Comment by jraska** [comment]
Thanks for understanding.

Best regards,

Josef

**Comment by trevjonez** [comment]
@nikoskyr maybe give https://github.com/Muddz/PixelShot a _shot?_
