### ISSUE TITLE
can not cature webview

### ISSUE THREAD

**Issue by Go-oG** [jraska/Falcon#48]
In one of my only WebView activities, I can't capture the contents of the WebView. Other Views can be capture.

**Comment by jraska** [comment]
Hello, Falcon relies completely on the `View.draw(Canvas)` method. Since WebView is quite special and most likely works differently than standard Android views, Falcon unfortunately cannot capture this view correctly. Sorry

**Comment by Go-oG** [comment]
Ok, thank you for your reply.
