### ISSUE TITLE
Migrate to Maven Central

### ISSUE THREAD

**Issue by jraska** [jraska/Falcon#52]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Edit: **UPDATE 4/27/2021:** We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.

**Comment by Jawnnypoo** [comment]
Lots of folks are looking to remove jcenter entirely from their builds, due to their recent brown-outs and unreliability. You should at least give mention to the alternative: `com.github.jraska.Falcon:falcon:2.1.1` from Jitpack.io

**Comment by jraska** [comment]
@Jawnnypoo there is a `com.github.jraska.Falcon:falcon:2.1.1` artifact on Jitpack? Do you have any link please? It seems there is a copy that I'm not aware about and not published by me.

**Comment by jraska** [comment]
Ah I see :) well let's say I wouldn't recommend Jitpack - I can recall few cases where it's availability was terrible and it killed our CI for few days and large part of dev experience.

Of course if Falcon would be the last remaining artifact on `jcenter`, then it could be a way to go, before Falcon appears on Maven Central

**Comment by Jawnnypoo** [comment]
Agreed, just thought I'd mention its a viable alternative.

**Comment by jraska** [comment]
https://issues.sonatype.org/browse/OSSRH-69305

**Comment by jraska** [comment]
Falcon is now in [Maven Central](https://repo1.maven.org/maven2/com/jraska/falcon/) starting with [the version `2.2.0`](https://github.com/jraska/Falcon/releases/tag/2.2.0).
```
implementation 'com.jraska:falcon:2.2.0'
```

**Comment by Jawnnypoo** [comment]
Yay thanks for doing this!
