### ISSUE TITLE
How to take screenshot of textureview alongwith otherviews ?

### ISSUE THREAD

**Issue by KanwalKhan-20** [jraska/Falcon#63]
How to take screenshot of textureview alongwith otherviews ?

**Comment by jraska** [comment]
Hi @KanwalKhan-20 , thanks for reaching out.

The answer is very similar to [this issue](https://github.com/jraska/Falcon/issues/13#issuecomment-238372895) also the one with [Google Maps](https://github.com/jraska/Falcon/issues/24#issuecomment-325746817) or with [Lottie](https://github.com/jraska/Falcon/issues/46#issuecomment-492989057)

Falcon cannot take screenshot from TextureView or any other View based on drawing content stream or OpenGL(SurfaceView, maps) coming from native APIs.
These Views unfortunately draw nothing when you call `draw(Canvas)` on them, which is the API Falcon uses for capturing the screen contents.
