### ISSUE TITLE
react-native webview canvas Black screen

### ISSUE THREAD

**Issue by BaLaLaLs** [jraska/Falcon#66]
i use in react-native，code
![image](https://user-images.githubusercontent.com/23353559/143914132-5f979d7e-a15f-4d94-8607-790ef90fd423.png)
When I trigger the screenshot i get this 
![image](https://user-images.githubusercontent.com/23353559/143914480-82b0d769-24fc-42aa-b040-cb96c016fbf6.png)
Normally, it should be
![image](https://user-images.githubusercontent.com/23353559/143914722-0346b488-548c-45c6-8d86-a1d949e6a9c5.png)
canvas tag not right render, i tried Instacapture  react-native-shot but Didn't solve my problem。

**Comment by jraska** [comment]
Hi @BaLaLaLs , thanks for reaching out.

I think the answer might very similar to [this issue](https://github.com/jraska/Falcon/issues/13#issuecomment-238372895) also the one with [Google Maps](https://github.com/jraska/Falcon/issues/24#issuecomment-325746817) or with [Lottie](https://github.com/jraska/Falcon/issues/46#issuecomment-492989057)

The react-native WebView might be using some different type of drawing - Falcon captures only pieces which draw themselves by `onDraw(Canvas)`.

Regular [WebView](https://developer.android.com/reference/android/webkit/WebView#capturePicture()) should be captured properly based [on documentation](https://developer.android.com/reference/android/webkit/WebView#capturePicture()):
<img width="195" alt="Screenshot 2021-12-06 at 22 14 35" src="https://user-images.githubusercontent.com/6277721/144923874-1abe9dc8-0f03-4265-a10f-96b2f977931a.png">

Though it seems like React Native WebView uses something different. 

Such special cases are unfortunately not supported and if the `onDraw(Canvas)` draws nothing, there is not much Falcon can do about this and I would seek a different way for taking screenshot for React Native. Or better different framework than RN is I could express my opinion :)
