### ISSUE TITLE
Failed to resolve Falcon

### ISSUE THREAD

**Issue by stephanepechard** [jraska/Falcon#8]
Hi,

After adding `compile 'com.jraska:falcon:1.0.1'` in my [client-android](https://github.com/PhotoBackup/client-android/blob/master/build.gradle) (on line 62, but not visible here as it is not commited), I get a gradle error: `Failed to resolve: com.jraska:falcon:1.0.1`.
Do I miss something in the integration?

Thanks

**Comment by jraska** [comment]
Hi, 

I think it is because Falcon is not on `mavenCentral()`, but on `jcenter()`. You can fix this with adding `jcenter()` into your `repositories` closure like 
```
repositories {
        mavenCentral()
        jcenter()
    }
```

**Comment by stephanepechard** [comment]
Thanks, it works now. Maybe you can add this to the documentation, to avoid other people to make the same mistake.
Thanks

**Comment by jraska** [comment]
No problem.
Thanks for using the library ;)
